spring:
  application:
    name: service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/inflearn_spring/h2/bin/hang-hae
    username: sa
    password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

logging:
  level:
    com.example.userservice: DEBUG
