spring:
  application:
    name: service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/inflearn_spring/h2/bin/hang-hae
    url: jdbc:h2:tcp://localhost/~/inflearn_spring/h2/bin/hang-hae
    username: sa
    password: 1234
  jpa:
    generate-ddl: true
    show-sql: true # ????? ?????
    properties:
      hibernate:
        ddl-auto: drop-create
        format_sql: true # SQL ???
        highlight_sql: true # ANSI ??? ?? ????
        use_sql_comments: true # SQL ??? /* */ ?? ??
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace
