server:
  port: 8118

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dbdb1114/reservationConfig.git
  rabbitmq:
    host: config-rabbitmq
    port: 5672
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
