server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-api:8888/eureka

spring:
  rabbitmq:
    host: config-rabbitmq
    port: 5672
    username: admin
    password: admin
  application:
    name: gateway-service

management:
  endpoints:
    web:
      exposure:
        include: health, refresh, beans, httpexchanges, busrefresh
